
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
homeassistant:
  name: Home
  latitude: 56.845823
  longitude: 53.235994
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 141
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Samara
  # Customization file
  customize: !include customize.yaml

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.16.0.0/12
        - 192.168.1.0/24
    - type: homeassistant

# Enables the frontend
frontend:

system_health:

# Enables configuration UI
config:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

lovelace:
    mode: yaml

cloud:

influxdb:
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - sensor.illumination_7811dcdf0e7e

light:
  - platform: xiaomi_miio
    name: mi_ceil62_bedroom
    host: 192.168.1.151
    token: 6ec6dffcddde46d01d5220d7d3e63fb2
    model: philips.light.ceiling
  - platform: xiaomi_miio
    name: mi_ceil50_kitchen
    host: 192.168.1.150
    token: a27c5d56784358a6893b0ca7ba0ef9d5
  - platform: xiaomi_miio
    name: mi_ceil62_lounge
    host: 192.168.1.152
    token: 3f69d5581288ba2e75e9140489b8997d
    model: philips.light.ceiling

switch:
  - platform: broadlink
    friendly_name: broadlink_lamp_hall
    host: 192.168.1.160
    mac: '34:EA:34:BD:DC:7D'
    type: sp2

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_allowed_chat_important
      - !secret telegram_bot_allowed_chat_log

binary_sensor:
 - platform: template
   sensors:
      hall_door_opening:
        friendly_name: Hall Door Opening
        value_template: >-
          {{
           (as_timestamp(sensor.time) - as_timestamp(states.binary_sensor.door_window_sensor_158d00012a236e.last_changed) < 10)
           and is_state('switch.broadlink_lamp_hall', 'on')
          }}
        device_class: motion
        entity_id: sensor.time

notify: !include notifiers.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml

shell_command:
  lounge_light_set_half_brightness: 'miceil --ip {{ states.light.mi_ceil62_lounge.attributes.host }}  --token {{ states.light.mi_ceil62_lounge.attributes.token }} set_brightness 50'


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

device_tracker:
  - platform: padavan_tracker
    consider_home: 10
    interval_seconds: 3
    url: http://192.168.1.1/ # web interface url (don't forget about `/` in the end)
    username: !secret webadmin_login # Web interface user name
    password: !secret webadmin_password # Web interface user pass
    new_device_defaults:
      track_new_devices: false
group:
  phone_trackers:
    name: Phone trackers
    entities:
      - device_tracker.dc_16_b2_ff_92_3a
      - device_tracker.30_a1_fa_11_90_1e
      - device_tracker.2c_57_31_cc_25_6a

#Zigbee2MQTT
mqtt:
  broker: core-mosquitto
  discovery: true

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 

sensor:
  - platform: command_line
    name: "Telegram Status"
    command: sh /config/scripts/telegram_health.sh
  - platform: mqtt
    name: Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless

input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
      - debug
      - info
      - warn
      - error
    initial: info
    icon: mdi:format-list-bulleted

input_text:
  zigbee2mqtt_old_name:
    name: Zigbee2mqtt Old Name
  zigbee2mqtt_new_name:
    name: Zigbee2mqtt New Name
  zigbee2mqtt_remove:
    name: Zigbee2mqtt Remove