resources:
  - url: /local/monster-card.js?v=1
    type: js
    
title: Home Assistant - Raspberry Pi4
views:
  - !include lovelace/main.yaml
  - !include lovelace/automation.yaml
  - !include lovelace/tracker.yaml
  - !include lovelace/zigbee2mqtt.yaml
