
- alias: Bedroom switch single click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8f631
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.mi_ceil62_bedroom

- alias: Bedroom switch double click when lamp on and half brightness
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8f631
      click_type: double
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.mi_ceil62_bedroom
        state: 'on'
      - condition: template
        value_template: '{{ states.light.mi_ceil62_bedroom.attributes.brightness <= 132 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.mi_ceil62_bedroom
        brightness: 255

- alias: Bedroom switch double click when lamp on and full brightness
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8f631
      click_type: double
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.mi_ceil62_bedroom
        state: 'on'
      - condition: template
        value_template: '{{ states.light.mi_ceil62_bedroom.attributes.brightness >= 250 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.mi_ceil62_bedroom
        brightness: 128

