
- alias: Bedroom switch single click
  trigger:
    platform: state
    entity_id: sensor.0x00158d0001d8f631_click
    to: 'single'
  action:
    - service: light.toggle
      entity_id: light.mi_ceil62_bedroom

- alias: Bedroom switch double click when lamp on and half brightness
  trigger:
    platform: state
    entity_id: sensor.0x00158d0001d8f631_click
    to: 'double'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.mi_ceil62_bedroom
        state: 'on'
      - condition: template
        value_template: '{{ states.light.mi_ceil62_bedroom.attributes.brightness <= 132 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.mi_ceil62_bedroom
        brightness: 255

- alias: Bedroom switch double click when lamp on and full brightness
  trigger:
    platform: state
    entity_id: sensor.0x00158d0001d8f631_click
    to: 'double'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.mi_ceil62_bedroom
        state: 'on'
      - condition: template
        value_template: '{{ states.light.mi_ceil62_bedroom.attributes.brightness >= 250 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.mi_ceil62_bedroom
        brightness: 128

