- alias: Hall switch single click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001d61fe6
      click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.broadlink_lamp_hall

