- alias: Hall switch single click
  trigger:
    platform: state
    entity_id: sensor.0x00158d0001d61fe6_click
    to: 'single'
  action:
    - service: switch.toggle
      entity_id: switch.broadlink_lamp_hall
- alias: Hall switch double click turn off all lights
  trigger:
    platform: state
    entity_id: sensor.0x00158d0001d61fe6_click
    to: 'double'
  action:
    - service: switch.turn_off
      entity_id: switch.broadlink_lamp_hall
    - service: light.turn_off
      entity_id: 
        - switch.broadlink_lamp_hall
        - light.mi_ceil50_kitchen
        - light.mi_ceil62_bedroom
        - light.mi_ceil62_lounge