- alias: Kitchen switch single click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0000f09703
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.mi_ceil50_kitchen

- alias: Kitchen switch double click when lamp on and half brightness
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0000f09703
      click_type: double
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.mi_ceil50_kitchen
        state: 'on'
      - condition: template
        value_template: '{{ states.light.mi_ceil50_kitchen.attributes.brightness < 255 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.mi_ceil50_kitchen
        brightness: 255

- alias: Kitchen switch double click when lamp on and full brightness
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0000f09703
      click_type: double
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.mi_ceil50_kitchen
        state: 'on'
      - condition: template
        value_template: '{{ states.light.mi_ceil50_kitchen.attributes.brightness >= 255 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.mi_ceil50_kitchen
        brightness: 128

- alias: Kitchen switch long click when lamp on
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0000f09703
      click_type: long_click_press
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: light.mi_ceil62_lounge
            state: 'on'
          - condition: state
            entity_id: light.mi_ceil50_kitchen
            state: 'on'
      - condition: template
        value_template: '{{ not is_state("automation.kitchen_switch_long_click_when_lamp_off", "last_triggered") or as_timestamp(now()) - as_timestamp(states.automation.kitchen_switch_long_click_when_lamp_off.last_triggered) >= 2 }}'
  action:
    - service: light.turn_off
      data:
        entity_id: light.mi_ceil62_lounge
    - service: light.turn_off
      data:
        entity_id: light.mi_ceil50_kitchen

- alias: Kitchen switch long click when lamp off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0000f09703
      click_type: long_click_press
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.mi_ceil62_lounge
        state: 'off'
      - condition: state
        entity_id: light.mi_ceil50_kitchen
        state: 'off'
      - condition: template
        value_template: '{{ not is_state("automation.kitchen_switch_long_click_when_lamp_on", "last_triggered") or  as_timestamp(now()) - as_timestamp(states.automation.kitchen_switch_long_click_when_lamp_off.last_triggered) >= 2 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.mi_ceil62_lounge
    - service: light.turn_on
      data:
        entity_id: light.mi_ceil50_kitchen

