- alias: Lounge turn off tv after 21-30
  trigger:
    platform: time
    at: '21:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d000117a7b0_switch

